name: User Story
description: Add a user story for the Operate First Cloud Instance. Use this to request new features and improvements.
title: "As a <persona>, I <want to>, <so that>."
labels: [kind/user-story]
body:
- type: textarea
  id: context
  attributes:
    description: |
      Please add any additional context for your story.
    label: Additional context
  validations:
    required: true
- type: textarea
  id: criteria
  attributes:
    label: Acceptance Criteria
    placeholder: |
      - [ ] At least once acceptance criteria should be present
  validations:
    required: true
- type: textarea
  id: links
  attributes:
    label: Relevant links
    description: |
      Add any links to resources, issues, etc. that you feel are
      relevant to this story.
  validations:
    required: true
